### ISSUE TITLE
The pre-training files seem to be missing.

### ISSUE THREAD

**Issue by Jingw0113** [AnzaShakeel/Deep-Learning-for-InSAR#1]
file_name_model = 'Trained_models/ALADDIn.hdf5'  # pre-trained model file name

OSError: Unable to open file (unable to open file: name = 'Trained_models/ALADDIn.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by AnzaShakeel** [comment]
Please email me so that I can share the trained model files.
email: anzashakeel92@gmail.com
